-- =====================================================================
-- 013 - a membership can be owed rather than paid
--
-- 012 made paid_on NOT NULL on the premise that a membership row is a
-- period that was paid for. That held while staff typed every row in
-- with the cash already in hand. It stops holding the moment a member
-- who is out of visits books from the app and promises to pay on
-- arrival: the period exists, the money does not.
--
-- NULL paid_on is that promise. amount_cents stays what the period
-- costs; paid_on says whether it has been collected yet.
-- membershipState() reads the two together and shows Unpaid, so when
-- the cash finally arrives nothing has to be written but the date.
--
-- coversDate() is deliberately untouched: an unpaid period is still
-- coverage. The member is allowed to train on the promise. What they
-- are not allowed to do is make a second one, and that rule lives in
-- the booking service.
-- =====================================================================
ALTER TABLE memberships ALTER COLUMN paid_on DROP NOT NULL;
