-- =====================================================================
-- 015 - member search has to work for Greek names
--
-- The gym is Greek and so are the members, but ILIKE compares accents
-- literally: 'Mαρία' ILIKE '%μαρια%' is false, and so is
-- 'ΜΑΡΙΑ' ILIKE '%μαρία%', because Greek capitals drop the tonos.
-- People type without accents constantly, especially on a phone, so
-- that is the normal search rather than an edge case.
--
-- unaccent folds the tonos on both sides: unaccent('Μαρία') is 'Μαρια'
-- and unaccent('ΜΑΡΊΑ') is 'ΜΑΡΙΑ'. Case folding is already correct on
-- its own - lower('ΜΑΡΊΑ') is 'μαρία' - so ILIKE only ever needed the
-- accents taken off.
--
-- No index goes with this. The search is ILIKE '%x%', a leading
-- wildcard no btree can serve, so it is a sequential scan either way
-- and there is nothing for an expression index to speed up. That also
-- sidesteps unaccent() being STABLE rather than IMMUTABLE, which only
-- bites when you try to index it.
--
-- Final sigma needs handling too, and unaccent does not do it. Postgres
-- lowercases capital sigma to the medial form, never the final one, so
-- a name stored in capitals - ΓΙΩΡΓΟΣ, as an ID document spells it -
-- folds to "γιωργοσ" and never matches "γιωργος" as anyone would
-- actually type it. greekFold() in lib/db.ts translates the final sigma
-- to the medial one on both sides, on top of this extension.
--
-- Sorting needs nothing: the database is en_US.utf8, which orders
-- Greek correctly and puts an accented capital in its alphabetical
-- place rather than ahead of every plain letter.
-- =====================================================================
CREATE EXTENSION IF NOT EXISTS unaccent;
